package erates.realmachines;

import net.minecraft.creativetab.CreativeTabs;

import com.google.common.collect.ImmutableList;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLInterModComms.IMCEvent;
import cpw.mods.fml.common.event.FMLInterModComms.IMCMessage;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import erates.realmachines.blocks.ModBlocks;
import erates.realmachines.client.interfaces.GuiHandler;
import erates.realmachines.creativetabs.RealMachinesCreativeTab;
import erates.realmachines.items.ModItems;
import erates.realmachines.lib.Reference;
import erates.realmachines.proxies.CommonProxy;
import erates.realmachines.recipes.RecipeHelper;

@Mod(modid = Reference.MODID, version = Reference.VERSION, name = Reference.MODNAME)
public class RealMachines {

	public static CreativeTabs tabRealMachines = new RealMachinesCreativeTab();

	@Instance(Reference.MODID)
	public static RealMachines instance;

	@SidedProxy(clientSide = "erates.realmachines.proxies.ClientProxy", serverSide = "erates.realmachines.proxies.CommonProxy")
	public static CommonProxy proxy;

	@Metadata
	public static ModMetadata metadata;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModBlocks.registerBlocks();
		ModItems.registerItems();

		proxy.initSounds();
		proxy.initRenderers();
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		createMetaData();

		RecipeHelper.registerRecipes();
		new GuiHandler();
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {

	}

	@EventHandler
	public void receiveMessages(IMCEvent event) {
		ImmutableList<IMCMessage> currentList = event.getMessages();

		for (IMCMessage message : currentList) {
			switch (message.key) {
				case "":
					String value = message.getStringValue();
					break;
			}
		}
	}

	private void createMetaData() {
		metadata.autogenerated = false;
		metadata.authorList.add("Erates");
		metadata.credits = "Created by Erates";
		metadata.description = "A mod that adds machines that need to be crafted in a way real life does things";
	}
}
